keywords: Hexo,Leijim,iOS,苹果,Swift,Linux
author: Leijim,ljm774256119@gmail.com
description: 你不勇敢，没人替你坚强。
avatar: https://secure.gravatar.com/avatar/e71df8021446fe9759a9928b1dd5c28d?s=180&r=G&d=

twitter: Ben_wenbin
rss: atom.xml
weibo: 枫柯
instagram: hwbinbenben

# Comment
duoshuo:
disqus: seansun
